version: "3.8"
services:
  mongo:
    image: mongo:6
    restart: always
    networks:
      - app_network
    volumes:
      - mongodb-data:/data/db

  backend:
    build: ./server
    restart: always
    networks:
      - app_network
    environment:
      MONGO_URI: mongodb://mongo:27017/smashpadelcenter
      FRONTEND_URL: http://frontend:5173
      PORT: 3001
      VAPID_PUBLIC_KEY: BHV4VfK4x3KvenR_4MOnl7D5hphAWNLQKRq1GyjGSDhzgfQGw8JsBhxwNrSjYZM-JHkpMFWZCxIe-Tp-BslQ3wQ
      VAPID_PRIVATE_KEY: 2IxzMFQyoYEQVvipXGgOBVWtepunvvUaWSXbx12QeY8
      VAPID_EMAIL: your_email@example.com
    depends_on:
      - mongo
    ports:
      - "3001:3001"

  frontend:
    build: ./
    environment:
      - REACT_APP_API_BASE_URL=http://backend:3001/api/v1
    restart: always
    networks:
      - app_network
    depends_on:
      - backend
    ports:
      - "5173:5173"

networks:
  app_network:
    driver: bridge

volumes:
  mongodb-data:
